### ISSUE TITLE
Use `isinstance()` and `id()` to short-circuit the common case in `__eq__`

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/record-type#4]
Assuming people will typically compare a record with another record of the same type, a fast path in `__eq__` would be to check if both objects define `__slots__`, that they are both tuples, and that they are the same object. That allows for skipping the values in the slot (thank tuple immmutability! 😀)

**Comment by brettcannon** [comment]
```
❯ py -m timeit -s "slots = ('a', 'b', 'c', 'd', 'e')" "frozenset(slots) == frozenset(slots)"
1000000 loops, best of 5: 317 nsec per loop
```

```
❯ py -m timeit -s "slots = ('a', 'b', 'c', 'd', 'e')" "frozenset(slots) == frozenset(slots)"
1000000 loops, best of 5: 317 nsec per loop
```

**Comment by brettcannon** [comment]
Actually, I'm not sure if `isinstance()` is even required, because if they are the same object for both instances, then they will inevitably have the same shape. Plus, Python only evaluates `__slots__` once, so mutating its value doesn't change what the class allows (and it just silly regardless).

```python
>>> class Spam: __slots__ = {'a'}
... 
>>> Spam().b = 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Spam' object has no attribute 'b'
>>> Spam.__slots__.add('b')
>>> Spam().b = 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Spam' object has no attribute 'b'
>>> Spam.__slots__
{'a', 'b'}
```
